export enum SOMETHING {
  TEENOI = 'TEENO',
  MOMO_PARADISE = 'MOMO_PARADISE',
  SUSHIRO = 'SUSHIRO',
  KATSU_MIDORI = 'KATSU_MIDORI',
  SHINKANZEN_SUSHI = 'SHINKANZEN_SUSHI',
  MCDONALD = 'MCDONALD',
  KFC = 'KFC',
  DOMINOS = 'DOMINOS',
  BURGER_KING = 'BURGER_KING',
}
