// somethings
export { default as burgerKing } from '@/assets/somethings/burger-king.jpg'
export { default as dominos } from '@/assets/somethings/dominos.jpg'
export { default as katsuMidori } from '@/assets/somethings/katsu-midori.jpg'
export { default as kfc } from '@/assets/somethings/kfc.jpg'
export { default as mcdonald } from '@/assets/somethings/mcdonald.jpg'
export { default as momoParadise } from '@/assets/somethings/momo-paradise.jpg'
export { default as shinkanzenSushi } from '@/assets/somethings/shinkanzen-sushi.jpg'
export { default as sushiro } from '@/assets/somethings/sushiro.jpg'
export { default as teenoi } from '@/assets/somethings/teenoi.jpg'
